/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    BundleComponentForm: typeof import('./components/dialogs/forms/BundleComponentForm.vue')['default']
    BundleComponentTable: typeof import('./components/datatable/BundleComponentTable.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CategoriesTable: typeof import('./components/datatable/CategoriesTable.vue')['default']
    CategoryForm: typeof import('./components/dialogs/forms/CategoryForm.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Datepicker: typeof import('primevue/datepicker')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoanDetail: typeof import('./components/dialogs/details/LoanDetail.vue')['default']
    LoanReviewForm: typeof import('./components/dialogs/forms/LoanReviewForm.vue')['default']
    LoanTable: typeof import('./components/datatable/LoanTable.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RecordConditionModal: typeof import('./components/dialogs/forms/RecordConditionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToolForm: typeof import('./components/dialogs/forms/ToolForm.vue')['default']
    ToolsTable: typeof import('./components/datatable/ToolsTable.vue')['default']
    ToolUnitFormModal: typeof import('./components/dialogs/forms/ToolUnitFormModal.vue')['default']
    ToolUnitsTable: typeof import('./components/datatable/ToolUnitsTable.vue')['default']
    UnitConditionHistoryModal: typeof import('./components/dialogs/details/UnitConditionHistoryModal.vue')['default']
    UpdateCredit: typeof import('./components/dialogs/forms/UpdateCredit.vue')['default']
    UserDetail: typeof import('./components/dialogs/details/UserDetail.vue')['default']
    UserForm: typeof import('./components/dialogs/forms/UserForm.vue')['default']
    UsersLoanTable: typeof import('./components/datatable/LoanTable.vue')['default']
    UsersTable: typeof import('./components/datatable/UsersTable.vue')['default']
    UserToolsTable: typeof import('./components/datatable/UserToolsTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
